site_name: dyvenia on docs
nav:
    - Home: home.md
    - "For Developers": 
        - "Building the Docs": building_docs.md
plugins:
  - search
  - mkdocs-jupyter
markdown_extensions:
  - toc:
      toc_depth: 3
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
  
 